const Stripe=require('stripe'); const {getPool,ensureSchema}=require('../_db');
module.exports.config={api:{bodyParser:false}};
function raw(req){return new Promise((resolve,reject)=>{const c=[];req.on('data',x=>c.push(Buffer.isBuffer(x)?x:Buffer.from(x)));req.on('end',()=>resolve(Buffer.concat(c)));req.on('error',reject);});}
async function markPaid(db,o,event){
 const client=await db.connect(); try{await client.query('BEGIN');
  const exists=await client.query('SELECT 1 FROM stripe_events WHERE id=$1',[event.id]); if(exists.rowCount){await client.query('ROLLBACK');return false;}
  const cr=await client.query(`INSERT INTO customers(id,name,email,mobile,address,postal,country,total_spend,order_count) VALUES($1,$2,$3,$4,$5,$6,$7,$8,1) ON CONFLICT DO NOTHING RETURNING id`,[require('crypto').randomUUID(),o.customer_name,o.customer_email,o.customer_mobile,o.address,o.postal,o.country,Number(o.total)]);
  let customerId=cr.rows[0]?.id; if(!customerId){const rr=await client.query(`SELECT id FROM customers WHERE (email IS NOT NULL AND LOWER(email)=LOWER($1)) OR (mobile IS NOT NULL AND mobile=$2) LIMIT 1`,[o.customer_email||'',o.customer_mobile||'']);customerId=rr.rows[0]?.id;}
  await client.query(`UPDATE orders SET status='PAID',payment_status='PAID',stripe_payment_intent_id=$1,customer_id=$2,paid_at=NOW(),updated_at=NOW() WHERE id=$3`,[event.data.object.payment_intent||null,customerId,o.id]);
  const items=Array.isArray(o.items)?o.items:[];
  for(const i of items){await client.query(`UPDATE products SET qty=GREATEST(0,qty-$1),soldout=(GREATEST(0,qty-$1)=0),updated_at=NOW() WHERE id=$2`,[Number(i.qty||1),i.id]);}
  if(customerId){const before=await client.query(`SELECT total_spend,order_count,aura_member,aura_balance FROM customers WHERE id=$1 FOR UPDATE`,[customerId]);if(before.rowCount){const c=before.rows[0];const newSpend=Number(c.total_spend)+Number(o.total);const newCount=Number(c.order_count)+1;let member=Boolean(c.aura_member);let balance=Number(c.aura_balance);if(newSpend>=500&&newCount>=2&&!member){member=true;balance+=25;await client.query(`INSERT INTO aura_transactions(id,customer_id,order_id,amount,type,note) VALUES(gen_random_uuid(),$1,$2,25,'WELCOME_CASHBACK','Aura activation after qualifying purchase')`,[customerId,o.id]);}if(member&&newCount>=2&&Number(o.total)>0){const cashback=Math.round(Number(o.subtotal)*0.07*100)/100; if(cashback>0){balance+=cashback;await client.query(`INSERT INTO aura_transactions(id,customer_id,order_id,amount,type,note) VALUES(gen_random_uuid(),$1,$2,$3,'CASHBACK','7% Aura cashback on non-clearance order')`,[customerId,o.id,cashback]);}}await client.query(`UPDATE customers SET total_spend=$1,order_count=$2,aura_member=$3,aura_balance=$4,aura_cashback_earned=aura_cashback_earned+$5,updated_at=NOW() WHERE id=$6`,[newSpend,newCount,member,balance,(member?Math.round(Number(o.subtotal)*0.07*100)/100:0),customerId]);}}
  await client.query(`INSERT INTO stripe_events(id,type) VALUES($1,$2)`,[event.id,event.type]); await client.query('COMMIT'); return true;
 }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
module.exports=async function(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!process.env.STRIPE_SECRET_KEY||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).json({error:'Stripe webhook is not configured'});try{await ensureSchema();const stripe=new Stripe(process.env.STRIPE_SECRET_KEY);const event=stripe.webhooks.constructEvent(req.rawBody || await raw(req),req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET);if(event.type==='checkout.session.completed'||event.type==='checkout.session.async_payment_succeeded'){const db=getPool();const sid=event.data.object.id;const r=await db.query(`SELECT * FROM orders WHERE stripe_session_id=$1`,[sid]);if(r.rowCount)await markPaid(db,r.rows[0],event);}return res.status(200).json({received:true,type:event.type,id:event.id});}catch(e){return res.status(400).json({error:`Webhook Error: ${e.message}`});}};
